// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'api/simple/audio_fingerprint.dart';
import 'api/simple/controller.dart';
import 'api/simple/equalizer.dart';
import 'api/simple/metadata.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -657582919;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'audio_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSimpleControllerCrossfadeToAudioFile({
    required String path,
    required PlatformInt64 durationMs,
  });

  Future<void> crateApiSimpleControllerDisposeAudio();

  Future<EqualizerConfig> crateApiSimpleEqualizerEqualizerConfigDefault();

  Future<FadeSettings> crateApiSimpleControllerFadeSettingsDefault();

  Future<void> crateApiSimpleControllerFinishFileWrite();

  Future<PlatformInt64> crateApiSimpleControllerGetAudioDurationMs();

  Future<EqualizerConfig> crateApiSimpleControllerGetAudioEqualizerConfig();

  Future<String> crateApiSimpleAudioFingerprintGetAudioFingerprint({
    required String path,
  });

  Future<Float32List> crateApiSimpleControllerGetAudioPcm({
    String? path,
    required BigInt sampleStride,
  });

  Future<int> crateApiSimpleControllerGetAudioPcmChannelCount({String? path});

  Future<PlatformInt64> crateApiSimpleControllerGetAudioPositionMs();

  Future<Float32List> crateApiSimpleControllerGetLatestFft();

  Future<String?> crateApiSimpleControllerGetLoadedAudioPath();

  Future<TrackMetadataUpdate> crateApiSimpleMetadataGetTrackMetadata({
    required String path,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleControllerHandleDeviceChanged();

  Future<void> crateApiSimpleControllerInitApp();

  Future<void> crateApiSimpleControllerInitLogger();

  Future<bool> crateApiSimpleControllerIsAudioPlaying();

  Future<void> crateApiSimpleControllerLoadAudioFile({required String path});

  Future<void> crateApiSimpleControllerPauseAudio({
    required PlatformInt64 fadeDurationMs,
  });

  Future<void> crateApiSimpleControllerPlayAudio({
    required PlatformInt64 fadeDurationMs,
  });

  Future<void> crateApiSimpleControllerPrepareForFileWrite();

  Future<void> crateApiSimpleMetadataRemoveAllTags({required String path});

  Future<void> crateApiSimpleControllerSeekAudioMs({
    required PlatformInt64 positionMs,
  });

  Future<void> crateApiSimpleControllerSetAudioEqualizerConfig({
    required EqualizerConfig config,
  });

  Future<void> crateApiSimpleControllerSetAudioVolume({required double volume});

  Stream<PlaybackState> crateApiSimpleSubscribePlaybackState();

  Future<bool> crateApiSimpleControllerToggleAudio();

  Future<TrackMetadataUpdate>
  crateApiSimpleMetadataTrackMetadataUpdateDefault();

  Future<TrackPicture> crateApiSimpleMetadataTrackPictureDefault();

  Future<void> crateApiSimpleMetadataUpdateTrackMetadata({
    required String path,
    required TrackMetadataUpdate metadata,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSimpleControllerCrossfadeToAudioFile({
    required String path,
    required PlatformInt64 durationMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_i_64(durationMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleControllerCrossfadeToAudioFileConstMeta,
        argValues: [path, durationMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerCrossfadeToAudioFileConstMeta =>
      const TaskConstMeta(
        debugName: "crossfade_to_audio_file",
        argNames: ["path", "durationMs"],
      );

  @override
  Future<void> crateApiSimpleControllerDisposeAudio() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleControllerDisposeAudioConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerDisposeAudioConstMeta =>
      const TaskConstMeta(debugName: "dispose_audio", argNames: []);

  @override
  Future<EqualizerConfig> crateApiSimpleEqualizerEqualizerConfigDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_equalizer_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleEqualizerEqualizerConfigDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEqualizerEqualizerConfigDefaultConstMeta =>
      const TaskConstMeta(debugName: "equalizer_config_default", argNames: []);

  @override
  Future<FadeSettings> crateApiSimpleControllerFadeSettingsDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_fade_settings,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleControllerFadeSettingsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerFadeSettingsDefaultConstMeta =>
      const TaskConstMeta(debugName: "fade_settings_default", argNames: []);

  @override
  Future<void> crateApiSimpleControllerFinishFileWrite() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleControllerFinishFileWriteConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerFinishFileWriteConstMeta =>
      const TaskConstMeta(debugName: "finish_file_write", argNames: []);

  @override
  Future<PlatformInt64> crateApiSimpleControllerGetAudioDurationMs() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleControllerGetAudioDurationMsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerGetAudioDurationMsConstMeta =>
      const TaskConstMeta(debugName: "get_audio_duration_ms", argNames: []);

  @override
  Future<EqualizerConfig> crateApiSimpleControllerGetAudioEqualizerConfig() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_equalizer_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleControllerGetAudioEqualizerConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerGetAudioEqualizerConfigConstMeta =>
      const TaskConstMeta(
        debugName: "get_audio_equalizer_config",
        argNames: [],
      );

  @override
  Future<String> crateApiSimpleAudioFingerprintGetAudioFingerprint({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleAudioFingerprintGetAudioFingerprintConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleAudioFingerprintGetAudioFingerprintConstMeta =>
      const TaskConstMeta(
        debugName: "get_audio_fingerprint",
        argNames: ["path"],
      );

  @override
  Future<Float32List> crateApiSimpleControllerGetAudioPcm({
    String? path,
    required BigInt sampleStride,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(path, serializer);
          sse_encode_usize(sampleStride, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleControllerGetAudioPcmConstMeta,
        argValues: [path, sampleStride],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerGetAudioPcmConstMeta =>
      const TaskConstMeta(
        debugName: "get_audio_pcm",
        argNames: ["path", "sampleStride"],
      );

  @override
  Future<int> crateApiSimpleControllerGetAudioPcmChannelCount({String? path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleControllerGetAudioPcmChannelCountConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerGetAudioPcmChannelCountConstMeta =>
      const TaskConstMeta(
        debugName: "get_audio_pcm_channel_count",
        argNames: ["path"],
      );

  @override
  Future<PlatformInt64> crateApiSimpleControllerGetAudioPositionMs() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleControllerGetAudioPositionMsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerGetAudioPositionMsConstMeta =>
      const TaskConstMeta(debugName: "get_audio_position_ms", argNames: []);

  @override
  Future<Float32List> crateApiSimpleControllerGetLatestFft() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleControllerGetLatestFftConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerGetLatestFftConstMeta =>
      const TaskConstMeta(debugName: "get_latest_fft", argNames: []);

  @override
  Future<String?> crateApiSimpleControllerGetLoadedAudioPath() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleControllerGetLoadedAudioPathConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerGetLoadedAudioPathConstMeta =>
      const TaskConstMeta(debugName: "get_loaded_audio_path", argNames: []);

  @override
  Future<TrackMetadataUpdate> crateApiSimpleMetadataGetTrackMetadata({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_track_metadata_update,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMetadataGetTrackMetadataConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMetadataGetTrackMetadataConstMeta =>
      const TaskConstMeta(debugName: "get_track_metadata", argNames: ["path"]);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleControllerHandleDeviceChanged() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleControllerHandleDeviceChangedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerHandleDeviceChangedConstMeta =>
      const TaskConstMeta(debugName: "handle_device_changed", argNames: []);

  @override
  Future<void> crateApiSimpleControllerInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleControllerInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiSimpleControllerInitLogger() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleControllerInitLoggerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerInitLoggerConstMeta =>
      const TaskConstMeta(debugName: "init_logger", argNames: []);

  @override
  Future<bool> crateApiSimpleControllerIsAudioPlaying() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleControllerIsAudioPlayingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerIsAudioPlayingConstMeta =>
      const TaskConstMeta(debugName: "is_audio_playing", argNames: []);

  @override
  Future<void> crateApiSimpleControllerLoadAudioFile({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleControllerLoadAudioFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerLoadAudioFileConstMeta =>
      const TaskConstMeta(debugName: "load_audio_file", argNames: ["path"]);

  @override
  Future<void> crateApiSimpleControllerPauseAudio({
    required PlatformInt64 fadeDurationMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(fadeDurationMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleControllerPauseAudioConstMeta,
        argValues: [fadeDurationMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerPauseAudioConstMeta =>
      const TaskConstMeta(
        debugName: "pause_audio",
        argNames: ["fadeDurationMs"],
      );

  @override
  Future<void> crateApiSimpleControllerPlayAudio({
    required PlatformInt64 fadeDurationMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(fadeDurationMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleControllerPlayAudioConstMeta,
        argValues: [fadeDurationMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerPlayAudioConstMeta =>
      const TaskConstMeta(
        debugName: "play_audio",
        argNames: ["fadeDurationMs"],
      );

  @override
  Future<void> crateApiSimpleControllerPrepareForFileWrite() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleControllerPrepareForFileWriteConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerPrepareForFileWriteConstMeta =>
      const TaskConstMeta(debugName: "prepare_for_file_write", argNames: []);

  @override
  Future<void> crateApiSimpleMetadataRemoveAllTags({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMetadataRemoveAllTagsConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMetadataRemoveAllTagsConstMeta =>
      const TaskConstMeta(debugName: "remove_all_tags", argNames: ["path"]);

  @override
  Future<void> crateApiSimpleControllerSeekAudioMs({
    required PlatformInt64 positionMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(positionMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleControllerSeekAudioMsConstMeta,
        argValues: [positionMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerSeekAudioMsConstMeta =>
      const TaskConstMeta(debugName: "seek_audio_ms", argNames: ["positionMs"]);

  @override
  Future<void> crateApiSimpleControllerSetAudioEqualizerConfig({
    required EqualizerConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_equalizer_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleControllerSetAudioEqualizerConfigConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerSetAudioEqualizerConfigConstMeta =>
      const TaskConstMeta(
        debugName: "set_audio_equalizer_config",
        argNames: ["config"],
      );

  @override
  Future<void> crateApiSimpleControllerSetAudioVolume({
    required double volume,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(volume, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleControllerSetAudioVolumeConstMeta,
        argValues: [volume],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerSetAudioVolumeConstMeta =>
      const TaskConstMeta(debugName: "set_audio_volume", argNames: ["volume"]);

  @override
  Stream<PlaybackState> crateApiSimpleSubscribePlaybackState() {
    final sink = RustStreamSink<PlaybackState>();
    handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_StreamSink_playback_state_Sse(sink, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleSubscribePlaybackStateConstMeta,
        argValues: [sink],
        apiImpl: this,
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleSubscribePlaybackStateConstMeta =>
      const TaskConstMeta(
        debugName: "subscribe_playback_state",
        argNames: ["sink"],
      );

  @override
  Future<bool> crateApiSimpleControllerToggleAudio() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleControllerToggleAudioConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleControllerToggleAudioConstMeta =>
      const TaskConstMeta(debugName: "toggle_audio", argNames: []);

  @override
  Future<TrackMetadataUpdate>
  crateApiSimpleMetadataTrackMetadataUpdateDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_track_metadata_update,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMetadataTrackMetadataUpdateDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleMetadataTrackMetadataUpdateDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "track_metadata_update_default",
        argNames: [],
      );

  @override
  Future<TrackPicture> crateApiSimpleMetadataTrackPictureDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_track_picture,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMetadataTrackPictureDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMetadataTrackPictureDefaultConstMeta =>
      const TaskConstMeta(debugName: "track_picture_default", argNames: []);

  @override
  Future<void> crateApiSimpleMetadataUpdateTrackMetadata({
    required String path,
    required TrackMetadataUpdate metadata,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_box_autoadd_track_metadata_update(metadata, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMetadataUpdateTrackMetadataConstMeta,
        argValues: [path, metadata],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMetadataUpdateTrackMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "update_track_metadata",
        argNames: ["path", "metadata"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<PlaybackState> dco_decode_StreamSink_playback_state_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  EqualizerConfig dco_decode_box_autoadd_equalizer_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_equalizer_config(raw);
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  TrackMetadataUpdate dco_decode_box_autoadd_track_metadata_update(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_track_metadata_update(raw);
  }

  @protected
  EqualizerConfig dco_decode_equalizer_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return EqualizerConfig(
      enabled: dco_decode_bool(arr[0]),
      bandCount: dco_decode_i_32(arr[1]),
      preampDb: dco_decode_f_32(arr[2]),
      bassBoostDb: dco_decode_f_32(arr[3]),
      bassBoostFrequencyHz: dco_decode_f_32(arr[4]),
      bassBoostQ: dco_decode_f_32(arr[5]),
      bandGainsDb: dco_decode_list_prim_f_32_strict(arr[6]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FadeMode dco_decode_fade_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FadeMode.values[raw as int];
  }

  @protected
  FadeSettings dco_decode_fade_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FadeSettings(
      fadeOnSwitch: dco_decode_bool(arr[0]),
      fadeOnPauseResume: dco_decode_bool(arr[1]),
      durationMs: dco_decode_i_64(arr[2]),
      mode: dco_decode_fade_mode(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TrackPicture> dco_decode_list_track_picture(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_track_picture).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  PlaybackState dco_decode_playback_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return PlaybackState(
      positionMs: dco_decode_i_64(arr[0]),
      durationMs: dco_decode_i_64(arr[1]),
      isPlaying: dco_decode_bool(arr[2]),
      volume: dco_decode_f_32(arr[3]),
      path: dco_decode_opt_String(arr[4]),
      error: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  TrackMetadataUpdate dco_decode_track_metadata_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 18)
      throw Exception('unexpected arr length: expect 18 but see ${arr.length}');
    return TrackMetadataUpdate(
      title: dco_decode_opt_String(arr[0]),
      artist: dco_decode_opt_String(arr[1]),
      album: dco_decode_opt_String(arr[2]),
      albumArtist: dco_decode_opt_String(arr[3]),
      trackNumber: dco_decode_opt_box_autoadd_i_32(arr[4]),
      trackTotal: dco_decode_opt_box_autoadd_i_32(arr[5]),
      discNumber: dco_decode_opt_box_autoadd_i_32(arr[6]),
      date: dco_decode_opt_String(arr[7]),
      year: dco_decode_opt_box_autoadd_i_32(arr[8]),
      comment: dco_decode_opt_String(arr[9]),
      lyrics: dco_decode_opt_String(arr[10]),
      composer: dco_decode_opt_String(arr[11]),
      lyricist: dco_decode_opt_String(arr[12]),
      performer: dco_decode_opt_String(arr[13]),
      conductor: dco_decode_opt_String(arr[14]),
      remixer: dco_decode_opt_String(arr[15]),
      genres: dco_decode_list_String(arr[16]),
      pictures: dco_decode_list_track_picture(arr[17]),
    );
  }

  @protected
  TrackPicture dco_decode_track_picture(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TrackPicture(
      bytes: dco_decode_list_prim_u_8_strict(arr[0]),
      mimeType: dco_decode_String(arr[1]),
      pictureType: dco_decode_String(arr[2]),
      description: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<PlaybackState> sse_decode_StreamSink_playback_state_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  EqualizerConfig sse_decode_box_autoadd_equalizer_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_equalizer_config(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  TrackMetadataUpdate sse_decode_box_autoadd_track_metadata_update(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_track_metadata_update(deserializer));
  }

  @protected
  EqualizerConfig sse_decode_equalizer_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_enabled = sse_decode_bool(deserializer);
    var var_bandCount = sse_decode_i_32(deserializer);
    var var_preampDb = sse_decode_f_32(deserializer);
    var var_bassBoostDb = sse_decode_f_32(deserializer);
    var var_bassBoostFrequencyHz = sse_decode_f_32(deserializer);
    var var_bassBoostQ = sse_decode_f_32(deserializer);
    var var_bandGainsDb = sse_decode_list_prim_f_32_strict(deserializer);
    return EqualizerConfig(
      enabled: var_enabled,
      bandCount: var_bandCount,
      preampDb: var_preampDb,
      bassBoostDb: var_bassBoostDb,
      bassBoostFrequencyHz: var_bassBoostFrequencyHz,
      bassBoostQ: var_bassBoostQ,
      bandGainsDb: var_bandGainsDb,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  FadeMode sse_decode_fade_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FadeMode.values[inner];
  }

  @protected
  FadeSettings sse_decode_fade_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fadeOnSwitch = sse_decode_bool(deserializer);
    var var_fadeOnPauseResume = sse_decode_bool(deserializer);
    var var_durationMs = sse_decode_i_64(deserializer);
    var var_mode = sse_decode_fade_mode(deserializer);
    return FadeSettings(
      fadeOnSwitch: var_fadeOnSwitch,
      fadeOnPauseResume: var_fadeOnPauseResume,
      durationMs: var_durationMs,
      mode: var_mode,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TrackPicture> sse_decode_list_track_picture(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TrackPicture>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_track_picture(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlaybackState sse_decode_playback_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_positionMs = sse_decode_i_64(deserializer);
    var var_durationMs = sse_decode_i_64(deserializer);
    var var_isPlaying = sse_decode_bool(deserializer);
    var var_volume = sse_decode_f_32(deserializer);
    var var_path = sse_decode_opt_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return PlaybackState(
      positionMs: var_positionMs,
      durationMs: var_durationMs,
      isPlaying: var_isPlaying,
      volume: var_volume,
      path: var_path,
      error: var_error,
    );
  }

  @protected
  TrackMetadataUpdate sse_decode_track_metadata_update(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_opt_String(deserializer);
    var var_artist = sse_decode_opt_String(deserializer);
    var var_album = sse_decode_opt_String(deserializer);
    var var_albumArtist = sse_decode_opt_String(deserializer);
    var var_trackNumber = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_trackTotal = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_discNumber = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_date = sse_decode_opt_String(deserializer);
    var var_year = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_comment = sse_decode_opt_String(deserializer);
    var var_lyrics = sse_decode_opt_String(deserializer);
    var var_composer = sse_decode_opt_String(deserializer);
    var var_lyricist = sse_decode_opt_String(deserializer);
    var var_performer = sse_decode_opt_String(deserializer);
    var var_conductor = sse_decode_opt_String(deserializer);
    var var_remixer = sse_decode_opt_String(deserializer);
    var var_genres = sse_decode_list_String(deserializer);
    var var_pictures = sse_decode_list_track_picture(deserializer);
    return TrackMetadataUpdate(
      title: var_title,
      artist: var_artist,
      album: var_album,
      albumArtist: var_albumArtist,
      trackNumber: var_trackNumber,
      trackTotal: var_trackTotal,
      discNumber: var_discNumber,
      date: var_date,
      year: var_year,
      comment: var_comment,
      lyrics: var_lyrics,
      composer: var_composer,
      lyricist: var_lyricist,
      performer: var_performer,
      conductor: var_conductor,
      remixer: var_remixer,
      genres: var_genres,
      pictures: var_pictures,
    );
  }

  @protected
  TrackPicture sse_decode_track_picture(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_mimeType = sse_decode_String(deserializer);
    var var_pictureType = sse_decode_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    return TrackPicture(
      bytes: var_bytes,
      mimeType: var_mimeType,
      pictureType: var_pictureType,
      description: var_description,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_playback_state_Sse(
    RustStreamSink<PlaybackState> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_equalizer_config(
    EqualizerConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_equalizer_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_track_metadata_update(
    TrackMetadataUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_track_metadata_update(self, serializer);
  }

  @protected
  void sse_encode_equalizer_config(
    EqualizerConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enabled, serializer);
    sse_encode_i_32(self.bandCount, serializer);
    sse_encode_f_32(self.preampDb, serializer);
    sse_encode_f_32(self.bassBoostDb, serializer);
    sse_encode_f_32(self.bassBoostFrequencyHz, serializer);
    sse_encode_f_32(self.bassBoostQ, serializer);
    sse_encode_list_prim_f_32_strict(self.bandGainsDb, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_fade_mode(FadeMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_fade_settings(FadeSettings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.fadeOnSwitch, serializer);
    sse_encode_bool(self.fadeOnPauseResume, serializer);
    sse_encode_i_64(self.durationMs, serializer);
    sse_encode_fade_mode(self.mode, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_track_picture(
    List<TrackPicture> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_track_picture(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_playback_state(PlaybackState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.positionMs, serializer);
    sse_encode_i_64(self.durationMs, serializer);
    sse_encode_bool(self.isPlaying, serializer);
    sse_encode_f_32(self.volume, serializer);
    sse_encode_opt_String(self.path, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_track_metadata_update(
    TrackMetadataUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.artist, serializer);
    sse_encode_opt_String(self.album, serializer);
    sse_encode_opt_String(self.albumArtist, serializer);
    sse_encode_opt_box_autoadd_i_32(self.trackNumber, serializer);
    sse_encode_opt_box_autoadd_i_32(self.trackTotal, serializer);
    sse_encode_opt_box_autoadd_i_32(self.discNumber, serializer);
    sse_encode_opt_String(self.date, serializer);
    sse_encode_opt_box_autoadd_i_32(self.year, serializer);
    sse_encode_opt_String(self.comment, serializer);
    sse_encode_opt_String(self.lyrics, serializer);
    sse_encode_opt_String(self.composer, serializer);
    sse_encode_opt_String(self.lyricist, serializer);
    sse_encode_opt_String(self.performer, serializer);
    sse_encode_opt_String(self.conductor, serializer);
    sse_encode_opt_String(self.remixer, serializer);
    sse_encode_list_String(self.genres, serializer);
    sse_encode_list_track_picture(self.pictures, serializer);
  }

  @protected
  void sse_encode_track_picture(TrackPicture self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_String(self.mimeType, serializer);
    sse_encode_String(self.pictureType, serializer);
    sse_encode_opt_String(self.description, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
