// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `append_from_path`, `clear_fft`, `compute_fft`, `controller`, `ensure_audio_output`, `extract_waveform_from_path`, `fold_packet_peaks_to_chunks`, `new`, `new`, `playback_position`, `push_mono_sample`, `with_player`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FftSource`, `PlayerController`, `WaveformChunk`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `channels`, `clone`, `current_span_len`, `fmt`, `next`, `sample_rate`, `total_duration`, `try_seek`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<void> loadAudioFile({required String path}) =>
    RustLib.instance.api.crateApiSimpleLoadAudioFile(path: path);

Future<void> playAudio() => RustLib.instance.api.crateApiSimplePlayAudio();

Future<void> pauseAudio() => RustLib.instance.api.crateApiSimplePauseAudio();

Future<bool> toggleAudio() => RustLib.instance.api.crateApiSimpleToggleAudio();

Future<void> seekAudioMs({required PlatformInt64 positionMs}) =>
    RustLib.instance.api.crateApiSimpleSeekAudioMs(positionMs: positionMs);

Future<void> setAudioVolume({required double volume}) =>
    RustLib.instance.api.crateApiSimpleSetAudioVolume(volume: volume);

Future<void> disposeAudio() =>
    RustLib.instance.api.crateApiSimpleDisposeAudio();

bool isAudioPlaying() => RustLib.instance.api.crateApiSimpleIsAudioPlaying();

PlatformInt64 getAudioDurationMs() =>
    RustLib.instance.api.crateApiSimpleGetAudioDurationMs();

PlatformInt64 getAudioPositionMs() =>
    RustLib.instance.api.crateApiSimpleGetAudioPositionMs();

Float32List getLatestFft() => RustLib.instance.api.crateApiSimpleGetLatestFft();

String? getLoadedAudioPath() =>
    RustLib.instance.api.crateApiSimpleGetLoadedAudioPath();

Future<Float32List> extractLoadedWaveform({
  required BigInt expectedChunks,
  required BigInt sampleStride,
}) => RustLib.instance.api.crateApiSimpleExtractLoadedWaveform(
  expectedChunks: expectedChunks,
  sampleStride: sampleStride,
);

Future<Float32List> extractWaveformForPath({
  required String path,
  required BigInt expectedChunks,
  required BigInt sampleStride,
}) => RustLib.instance.api.crateApiSimpleExtractWaveformForPath(
  path: path,
  expectedChunks: expectedChunks,
  sampleStride: sampleStride,
);
