// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'equalizer.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `any_deck_playing`, `apply_master_volume`, `clear`, `controller`, `create_player`, `describe_output_device`, `dispose_audio`, `drive_crossfade`, `drive_volume_fade`, `ensure_audio_output`, `invalidate_waveform_cache`, `is_playing`, `new`, `open_current_default_output`, `open_deck_from_path`, `pause_all`, `play_all`, `playback_position`, `playback_state_snapshot`, `poll_output_device`, `public_deck`, `public_path`, `public_position`, `replace_current_from_path`, `set_master_volume`, `settle_to_public_deck`, `snapshot_loaded_path`, `snapshot_playback_state`, `start_crossfade`, `start_default_output_monitor`, `start_volume_fade`, `toggle_all`, `warm_waveform_cache_for_public_path`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PlaybackDeck`, `PlayerController`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

Future<void> initLogger() =>
    RustLib.instance.api.crateApiSimpleControllerInitLogger();

Future<void> initApp() =>
    RustLib.instance.api.crateApiSimpleControllerInitApp();

Future<void> loadAudioFile({required String path}) =>
    RustLib.instance.api.crateApiSimpleControllerLoadAudioFile(path: path);

Future<void> crossfadeToAudioFile({
  required String path,
  required PlatformInt64 durationMs,
}) => RustLib.instance.api.crateApiSimpleControllerCrossfadeToAudioFile(
  path: path,
  durationMs: durationMs,
);

Future<void> playAudio() =>
    RustLib.instance.api.crateApiSimpleControllerPlayAudio();

Future<void> pauseAudio() =>
    RustLib.instance.api.crateApiSimpleControllerPauseAudio();

Future<void> setAudioFadeSettings({required FadeSettings settings}) => RustLib
    .instance
    .api
    .crateApiSimpleControllerSetAudioFadeSettings(settings: settings);

Future<bool> toggleAudio() =>
    RustLib.instance.api.crateApiSimpleControllerToggleAudio();

Future<void> seekAudioMs({required PlatformInt64 positionMs}) => RustLib
    .instance
    .api
    .crateApiSimpleControllerSeekAudioMs(positionMs: positionMs);

Future<void> setAudioVolume({required double volume}) =>
    RustLib.instance.api.crateApiSimpleControllerSetAudioVolume(volume: volume);

Future<EqualizerConfig> getAudioEqualizerConfig() =>
    RustLib.instance.api.crateApiSimpleControllerGetAudioEqualizerConfig();

Future<void> setAudioEqualizerConfig({required EqualizerConfig config}) =>
    RustLib.instance.api.crateApiSimpleControllerSetAudioEqualizerConfig(
      config: config,
    );

Future<void> disposeAudio() =>
    RustLib.instance.api.crateApiSimpleControllerDisposeAudio();

Future<bool> isAudioPlaying() =>
    RustLib.instance.api.crateApiSimpleControllerIsAudioPlaying();

Future<PlatformInt64> getAudioDurationMs() =>
    RustLib.instance.api.crateApiSimpleControllerGetAudioDurationMs();

Future<PlatformInt64> getAudioPositionMs() =>
    RustLib.instance.api.crateApiSimpleControllerGetAudioPositionMs();

Future<Float32List> getLatestFft() =>
    RustLib.instance.api.crateApiSimpleControllerGetLatestFft();

Future<String?> getLoadedAudioPath() =>
    RustLib.instance.api.crateApiSimpleControllerGetLoadedAudioPath();

Future<void> handleDeviceChanged() =>
    RustLib.instance.api.crateApiSimpleControllerHandleDeviceChanged();

enum FadeMode { sequential, crossfade }

class FadeSettings {
  final bool fadeOnSwitch;
  final bool fadeOnPauseResume;
  final PlatformInt64 durationMs;
  final FadeMode mode;

  const FadeSettings({
    required this.fadeOnSwitch,
    required this.fadeOnPauseResume,
    required this.durationMs,
    required this.mode,
  });

  static Future<FadeSettings> default_() =>
      RustLib.instance.api.crateApiSimpleControllerFadeSettingsDefault();

  @override
  int get hashCode =>
      fadeOnSwitch.hashCode ^
      fadeOnPauseResume.hashCode ^
      durationMs.hashCode ^
      mode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FadeSettings &&
          runtimeType == other.runtimeType &&
          fadeOnSwitch == other.fadeOnSwitch &&
          fadeOnPauseResume == other.fadeOnPauseResume &&
          durationMs == other.durationMs &&
          mode == other.mode;
}

class PlaybackState {
  final PlatformInt64 positionMs;
  final PlatformInt64 durationMs;
  final bool isPlaying;
  final double volume;
  final String? path;
  final String? error;

  const PlaybackState({
    required this.positionMs,
    required this.durationMs,
    required this.isPlaying,
    required this.volume,
    this.path,
    this.error,
  });

  @override
  int get hashCode =>
      positionMs.hashCode ^
      durationMs.hashCode ^
      isPlaying.hashCode ^
      volume.hashCode ^
      path.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackState &&
          runtimeType == other.runtimeType &&
          positionMs == other.positionMs &&
          durationMs == other.durationMs &&
          isPlaying == other.isPlaying &&
          volume == other.volume &&
          path == other.path &&
          error == other.error;
}
