// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `band_center_frequency`, `band_coefficients`, `current_config`, `db_to_gain`, `estimate_peak_gain`, `from_config`, `identity`, `identity`, `low_shelf`, `magnitude_at`, `new`, `new`, `new`, `peaking`, `process_current_sample`, `process_sample`, `process`, `refresh_if_needed`, `reset`, `reset`, `set_config`, `soft_limit_sample`, `update_coeffs`, `update_from_config`, `version`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BiquadCoefficients`, `Biquad`, `EqSource`, `EqualizerChain`, `EqualizerShared`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `channels`, `clone`, `clone`, `clone`, `clone`, `current_span_len`, `fmt`, `next`, `sample_rate`, `total_duration`, `try_seek`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `sanitized`

class EqualizerConfig {
  final bool enabled;
  final int bandCount;
  final double preampDb;
  final double bassBoostDb;
  final double bassBoostFrequencyHz;
  final double bassBoostQ;
  final Float32List bandGainsDb;

  const EqualizerConfig({
    required this.enabled,
    required this.bandCount,
    required this.preampDb,
    required this.bassBoostDb,
    required this.bassBoostFrequencyHz,
    required this.bassBoostQ,
    required this.bandGainsDb,
  });

  static Future<EqualizerConfig> default_() =>
      RustLib.instance.api.crateApiSimpleEqualizerEqualizerConfigDefault();

  @override
  int get hashCode =>
      enabled.hashCode ^
      bandCount.hashCode ^
      preampDb.hashCode ^
      bassBoostDb.hashCode ^
      bassBoostFrequencyHz.hashCode ^
      bassBoostQ.hashCode ^
      bandGainsDb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EqualizerConfig &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          bandCount == other.bandCount &&
          preampDb == other.preampDb &&
          bassBoostDb == other.bassBoostDb &&
          bassBoostFrequencyHz == other.bassBoostFrequencyHz &&
          bassBoostQ == other.bassBoostQ &&
          bandGainsDb == other.bandGainsDb;
}
