// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `first_extended_text_value`, `first_tag_value`, `first_text_frame_value`, `id3_picture_type_to_label`, `lofty_picture_type_to_label`, `read_track_metadata_with_id3`, `read_track_metadata_with_lofty`, `should_use_id3`, `update_track_metadata_with_id3`, `update_track_metadata_with_lofty`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<void> updateTrackMetadata({
  required String path,
  required TrackMetadataUpdate metadata,
}) => RustLib.instance.api.crateApiSimpleMetadataUpdateTrackMetadata(
  path: path,
  metadata: metadata,
);

Future<TrackMetadataUpdate> getTrackMetadata({required String path}) =>
    RustLib.instance.api.crateApiSimpleMetadataGetTrackMetadata(path: path);

Future<void> removeAllTags({required String path}) =>
    RustLib.instance.api.crateApiSimpleMetadataRemoveAllTags(path: path);

class TrackMetadataUpdate {
  final String? title;
  final String? artist;
  final String? album;
  final String? albumArtist;
  final int? trackNumber;
  final int? trackTotal;
  final int? discNumber;
  final String? date;
  final int? year;
  final String? comment;
  final String? lyrics;
  final String? composer;
  final String? lyricist;
  final String? performer;
  final String? conductor;
  final String? remixer;
  final List<String> genres;
  final List<TrackPicture> pictures;

  const TrackMetadataUpdate({
    this.title,
    this.artist,
    this.album,
    this.albumArtist,
    this.trackNumber,
    this.trackTotal,
    this.discNumber,
    this.date,
    this.year,
    this.comment,
    this.lyrics,
    this.composer,
    this.lyricist,
    this.performer,
    this.conductor,
    this.remixer,
    required this.genres,
    required this.pictures,
  });

  static Future<TrackMetadataUpdate> default_() =>
      RustLib.instance.api.crateApiSimpleMetadataTrackMetadataUpdateDefault();

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      albumArtist.hashCode ^
      trackNumber.hashCode ^
      trackTotal.hashCode ^
      discNumber.hashCode ^
      date.hashCode ^
      year.hashCode ^
      comment.hashCode ^
      lyrics.hashCode ^
      composer.hashCode ^
      lyricist.hashCode ^
      performer.hashCode ^
      conductor.hashCode ^
      remixer.hashCode ^
      genres.hashCode ^
      pictures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackMetadataUpdate &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          albumArtist == other.albumArtist &&
          trackNumber == other.trackNumber &&
          trackTotal == other.trackTotal &&
          discNumber == other.discNumber &&
          date == other.date &&
          year == other.year &&
          comment == other.comment &&
          lyrics == other.lyrics &&
          composer == other.composer &&
          lyricist == other.lyricist &&
          performer == other.performer &&
          conductor == other.conductor &&
          remixer == other.remixer &&
          genres == other.genres &&
          pictures == other.pictures;
}

class TrackPicture {
  final Uint8List bytes;
  final String mimeType;
  final String pictureType;
  final String? description;

  const TrackPicture({
    required this.bytes,
    required this.mimeType,
    required this.pictureType,
    this.description,
  });

  static Future<TrackPicture> default_() =>
      RustLib.instance.api.crateApiSimpleMetadataTrackPictureDefault();

  @override
  int get hashCode =>
      bytes.hashCode ^
      mimeType.hashCode ^
      pictureType.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackPicture &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          mimeType == other.mimeType &&
          pictureType == other.pictureType &&
          description == other.description;
}
