// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `chunk_bounds`, `compute_packet_envelope`, `extract_waveform_from_path`, `fold_packet_energy_to_chunks`, `normalize_waveform_levels`, `time_to_chunk`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `WaveformChunk`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<Float32List> extractLoadedWaveform({
  required BigInt expectedChunks,
  required BigInt sampleStride,
}) => RustLib.instance.api.crateApiSimpleWaveformExtractLoadedWaveform(
  expectedChunks: expectedChunks,
  sampleStride: sampleStride,
);

Future<Float32List> extractWaveformForPath({
  required String path,
  required BigInt expectedChunks,
  required BigInt sampleStride,
}) => RustLib.instance.api.crateApiSimpleWaveformExtractWaveformForPath(
  path: path,
  expectedChunks: expectedChunks,
  sampleStride: sampleStride,
);
